import { createFileRoute, Link } from "@tanstack/react-router"

export const Route = createFileRoute("/")({
  component: Home,
})

function Home() {
  return (
    <main style={{ fontFamily: "sans-serif", padding: "2rem", maxWidth: "48rem" }}>
      <h1 style={{ fontSize: "2rem", fontWeight: "bold", marginBottom: "0.5rem" }}>
        BTST Playground
      </h1>
      <p style={{ color: "#666", marginBottom: "1.5rem" }}>
        A demo project generated by the BTST Playground. Navigate to a plugin route below.
      </p>
      <nav>
        <Link
          to="/pages/$"
          params={{ _splat: "route-docs" }}
          style={{ color: "#2563eb", textDecoration: "underline" }}
        >
          /pages/route-docs — Browse all available routes
        </Link>
      </nav>
    </main>
  )
}
