name: niteowl-dev

services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks: [niteowl-dev]

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - ./redis:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$${REDIS_PASSWORD}\" ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks: [niteowl-dev]


  node-upstream:
    image: 'node:26-trixie'
    working_dir: /app
    command:
      - sleep
      - infinity
    stdin_open: true
    tty: true
    ports:
      - "3040:3000"
    volumes:
      - './node-upstream/app:/app'
    env_file:
      - .env
    restart: unless-stopped
    networks: [niteowl-dev]

  auth:
    image: 'node:26-trixie'
    working_dir: /app
    command: ["npm", "start"]
#    command:
#      - sleep
#      - infinity
    stdin_open: true
    tty: true
    volumes:
      - './auth/app:/app'
    restart: unless-stopped
    networks: [niteowl-dev]
    ports:
      - "3031:3000"
    env_file:
      - ./.env-better-auth

  admin:
    image: 'node:26-trixie'
    working_dir: /app
#    command: ["sh", "-c", "npm run build && npm start"]
    command:
      - sleep
      - infinity
    stdin_open: true
    tty: true
    volumes:
      - './admin/app:/app'
    restart: unless-stopped
    networks: [niteowl-dev]
    ports:
      - "3030:3000"
    env_file:
      - ./.env-btst
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  niteowl-dev:
    name: niteowl-dev
