services:
  glauth-postgres-test:
    image: glauth/glauth-plugins:v2.5.2
    restart: "no"
    volumes:
      - ./glauth-postgres/config.cfg:/app/config/config.cfg:ro
    ports:
      - "390:3893"
    networks:
      - niteowl-dev
    depends_on:
      postgres:
        condition: service_healthy
