/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesRouteRouteImport } from './routes/pages/route'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiSeedBlogRouteImport } from './routes/api/seed-blog'
import { Route as ApiSeedCmsRouteImport } from './routes/api/seed-cms'
import { Route as ApiSeedFormBuilderRouteImport } from './routes/api/seed-form-builder'
import { Route as ApiSeedKanbanRouteImport } from './routes/api/seed-kanban'
import { Route as ApiSeedUiBuilderRouteImport } from './routes/api/seed-ui-builder'
import { Route as FormDemoSlugRouteImport } from './routes/form-demo.$slug'
import { Route as PagesSplatRouteImport } from './routes/pages/$'
import { Route as PreviewSlugRouteImport } from './routes/preview.$slug'
import { Route as ApiDataSplatRouteImport } from './routes/api/data/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRouteRoute = PagesRouteRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedBlogRoute = ApiSeedBlogRouteImport.update({
  id: '/api/seed-blog',
  path: '/api/seed-blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedCmsRoute = ApiSeedCmsRouteImport.update({
  id: '/api/seed-cms',
  path: '/api/seed-cms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedFormBuilderRoute = ApiSeedFormBuilderRouteImport.update({
  id: '/api/seed-form-builder',
  path: '/api/seed-form-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedKanbanRoute = ApiSeedKanbanRouteImport.update({
  id: '/api/seed-kanban',
  path: '/api/seed-kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedUiBuilderRoute = ApiSeedUiBuilderRouteImport.update({
  id: '/api/seed-ui-builder',
  path: '/api/seed-ui-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const FormDemoSlugRoute = FormDemoSlugRouteImport.update({
  id: '/form-demo/$slug',
  path: '/form-demo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSplatRoute = PagesSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PagesRouteRoute,
} as any)
const PreviewSlugRoute = PreviewSlugRouteImport.update({
  id: '/preview/$slug',
  path: '/preview/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataSplatRoute = ApiDataSplatRouteImport.update({
  id: '/api/data/$',
  path: '/api/data/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pages': typeof PagesRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/seed-blog': typeof ApiSeedBlogRoute
  '/api/seed-cms': typeof ApiSeedCmsRoute
  '/api/seed-form-builder': typeof ApiSeedFormBuilderRoute
  '/api/seed-kanban': typeof ApiSeedKanbanRoute
  '/api/seed-ui-builder': typeof ApiSeedUiBuilderRoute
  '/form-demo/$slug': typeof FormDemoSlugRoute
  '/pages/$': typeof PagesSplatRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/api/data/$': typeof ApiDataSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pages': typeof PagesRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/seed-blog': typeof ApiSeedBlogRoute
  '/api/seed-cms': typeof ApiSeedCmsRoute
  '/api/seed-form-builder': typeof ApiSeedFormBuilderRoute
  '/api/seed-kanban': typeof ApiSeedKanbanRoute
  '/api/seed-ui-builder': typeof ApiSeedUiBuilderRoute
  '/form-demo/$slug': typeof FormDemoSlugRoute
  '/pages/$': typeof PagesSplatRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/api/data/$': typeof ApiDataSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pages': typeof PagesRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/seed-blog': typeof ApiSeedBlogRoute
  '/api/seed-cms': typeof ApiSeedCmsRoute
  '/api/seed-form-builder': typeof ApiSeedFormBuilderRoute
  '/api/seed-kanban': typeof ApiSeedKanbanRoute
  '/api/seed-ui-builder': typeof ApiSeedUiBuilderRoute
  '/form-demo/$slug': typeof FormDemoSlugRoute
  '/pages/$': typeof PagesSplatRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/api/data/$': typeof ApiDataSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pages'
    | '/sitemap.xml'
    | '/api/seed-blog'
    | '/api/seed-cms'
    | '/api/seed-form-builder'
    | '/api/seed-kanban'
    | '/api/seed-ui-builder'
    | '/form-demo/$slug'
    | '/pages/$'
    | '/preview/$slug'
    | '/api/data/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pages'
    | '/sitemap.xml'
    | '/api/seed-blog'
    | '/api/seed-cms'
    | '/api/seed-form-builder'
    | '/api/seed-kanban'
    | '/api/seed-ui-builder'
    | '/form-demo/$slug'
    | '/pages/$'
    | '/preview/$slug'
    | '/api/data/$'
  id:
    | '__root__'
    | '/'
    | '/pages'
    | '/sitemap.xml'
    | '/api/seed-blog'
    | '/api/seed-cms'
    | '/api/seed-form-builder'
    | '/api/seed-kanban'
    | '/api/seed-ui-builder'
    | '/form-demo/$slug'
    | '/pages/$'
    | '/preview/$slug'
    | '/api/data/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagesRouteRoute: typeof PagesRouteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSeedBlogRoute: typeof ApiSeedBlogRoute
  ApiSeedCmsRoute: typeof ApiSeedCmsRoute
  ApiSeedFormBuilderRoute: typeof ApiSeedFormBuilderRoute
  ApiSeedKanbanRoute: typeof ApiSeedKanbanRoute
  ApiSeedUiBuilderRoute: typeof ApiSeedUiBuilderRoute
  FormDemoSlugRoute: typeof FormDemoSlugRoute
  PreviewSlugRoute: typeof PreviewSlugRoute
  ApiDataSplatRoute: typeof ApiDataSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed-blog': {
      id: '/api/seed-blog'
      path: '/api/seed-blog'
      fullPath: '/api/seed-blog'
      preLoaderRoute: typeof ApiSeedBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed-cms': {
      id: '/api/seed-cms'
      path: '/api/seed-cms'
      fullPath: '/api/seed-cms'
      preLoaderRoute: typeof ApiSeedCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed-form-builder': {
      id: '/api/seed-form-builder'
      path: '/api/seed-form-builder'
      fullPath: '/api/seed-form-builder'
      preLoaderRoute: typeof ApiSeedFormBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed-kanban': {
      id: '/api/seed-kanban'
      path: '/api/seed-kanban'
      fullPath: '/api/seed-kanban'
      preLoaderRoute: typeof ApiSeedKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed-ui-builder': {
      id: '/api/seed-ui-builder'
      path: '/api/seed-ui-builder'
      fullPath: '/api/seed-ui-builder'
      preLoaderRoute: typeof ApiSeedUiBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-demo/$slug': {
      id: '/form-demo/$slug'
      path: '/form-demo/$slug'
      fullPath: '/form-demo/$slug'
      preLoaderRoute: typeof FormDemoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$': {
      id: '/pages/$'
      path: '/$'
      fullPath: '/pages/$'
      preLoaderRoute: typeof PagesSplatRouteImport
      parentRoute: typeof PagesRouteRoute
    }
    '/preview/$slug': {
      id: '/preview/$slug'
      path: '/preview/$slug'
      fullPath: '/preview/$slug'
      preLoaderRoute: typeof PreviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/$': {
      id: '/api/data/$'
      path: '/api/data/$'
      fullPath: '/api/data/$'
      preLoaderRoute: typeof ApiDataSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PagesRouteRouteChildren {
  PagesSplatRoute: typeof PagesSplatRoute
}

const PagesRouteRouteChildren: PagesRouteRouteChildren = {
  PagesSplatRoute: PagesSplatRoute,
}

const PagesRouteRouteWithChildren = PagesRouteRoute._addFileChildren(
  PagesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagesRouteRoute: PagesRouteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSeedBlogRoute: ApiSeedBlogRoute,
  ApiSeedCmsRoute: ApiSeedCmsRoute,
  ApiSeedFormBuilderRoute: ApiSeedFormBuilderRoute,
  ApiSeedKanbanRoute: ApiSeedKanbanRoute,
  ApiSeedUiBuilderRoute: ApiSeedUiBuilderRoute,
  FormDemoSlugRoute: FormDemoSlugRoute,
  PreviewSlugRoute: PreviewSlugRoute,
  ApiDataSplatRoute: ApiDataSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
