/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as SettingsPathRouteImport } from './routes/settings/$path'
import { Route as OrganizationSlugPathRouteImport } from './routes/organization/$slug/$path'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPathRoute = SettingsPathRouteImport.update({
  id: '/settings/$path',
  path: '/settings/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSlugPathRoute = OrganizationSlugPathRouteImport.update({
  id: '/organization/$slug/$path',
  path: '/organization/$slug/$path',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/organization/$slug/$path': typeof OrganizationSlugPathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/organization/$slug/$path': typeof OrganizationSlugPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof SettingsPathRoute
  '/organization/$slug/$path': typeof OrganizationSlugPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/$'
    | '/auth/$path'
    | '/settings/$path'
    | '/organization/$slug/$path'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/$'
    | '/auth/$path'
    | '/settings/$path'
    | '/organization/$slug/$path'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/$'
    | '/auth/$path'
    | '/settings/$path'
    | '/organization/$slug/$path'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthPathRoute: typeof AuthPathRoute
  SettingsPathRoute: typeof SettingsPathRoute
  OrganizationSlugPathRoute: typeof OrganizationSlugPathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$path': {
      id: '/settings/$path'
      path: '/settings/$path'
      fullPath: '/settings/$path'
      preLoaderRoute: typeof SettingsPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$slug/$path': {
      id: '/organization/$slug/$path'
      path: '/organization/$slug/$path'
      fullPath: '/organization/$slug/$path'
      preLoaderRoute: typeof OrganizationSlugPathRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthPathRoute: AuthPathRoute,
  SettingsPathRoute: SettingsPathRoute,
  OrganizationSlugPathRoute: OrganizationSlugPathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
