/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as DotwellKnownOauthAuthorizationServerSplatRouteImport } from './routes/[.]well-known/oauth-authorization-server/$'
import { Route as AppOrganizationsIndexRouteImport } from './routes/_app/organizations.index'
import { Route as AppOrganizationsOrganizationIdRouteImport } from './routes/_app/organizations.$organizationId'
import { Route as AppPluginsIndexRouteImport } from './routes/_app/plugins.index'
import { Route as AppPluginsPluginIdRouteImport } from './routes/_app/plugins.$pluginId'
import { Route as AppSettingsPathRouteImport } from './routes/_app.settings.$path'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users.index'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users.$userId'
import { Route as AppOrganizationSlugPathRouteImport } from './routes/_app/organization/$slug/$path'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerSplatRoute =
  DotwellKnownOauthAuthorizationServerSplatRouteImport.update({
    id: '/.well-known/oauth-authorization-server/$',
    path: '/.well-known/oauth-authorization-server/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsOrganizationIdRoute =
  AppOrganizationsOrganizationIdRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppPluginsIndexRoute = AppPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => AppRoute,
} as any)
const AppPluginsPluginIdRoute = AppPluginsPluginIdRouteImport.update({
  id: '/plugins/$pluginId',
  path: '/plugins/$pluginId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPathRoute = AppSettingsPathRouteImport.update({
  id: '/settings/$path',
  path: '/settings/$path',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationSlugPathRoute = AppOrganizationSlugPathRouteImport.update({
  id: '/organization/$slug/$path',
  path: '/organization/$slug/$path',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$path': typeof AuthPathRoute
  '/.well-known/oauth-authorization-server/$': typeof DotwellKnownOauthAuthorizationServerSplatRoute
  '/organizations/$organizationId': typeof AppOrganizationsOrganizationIdRoute
  '/plugins/$pluginId': typeof AppPluginsPluginIdRoute
  '/settings/$path': typeof AppSettingsPathRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/organizations/': typeof AppOrganizationsIndexRoute
  '/plugins/': typeof AppPluginsIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/organization/$slug/$path': typeof AppOrganizationSlugPathRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$path': typeof AuthPathRoute
  '/': typeof AppIndexRoute
  '/.well-known/oauth-authorization-server/$': typeof DotwellKnownOauthAuthorizationServerSplatRoute
  '/organizations/$organizationId': typeof AppOrganizationsOrganizationIdRoute
  '/plugins/$pluginId': typeof AppPluginsPluginIdRoute
  '/settings/$path': typeof AppSettingsPathRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/organizations': typeof AppOrganizationsIndexRoute
  '/plugins': typeof AppPluginsIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/organization/$slug/$path': typeof AppOrganizationSlugPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$path': typeof AuthPathRoute
  '/_app/': typeof AppIndexRoute
  '/.well-known/oauth-authorization-server/$': typeof DotwellKnownOauthAuthorizationServerSplatRoute
  '/_app/organizations/$organizationId': typeof AppOrganizationsOrganizationIdRoute
  '/_app/plugins/$pluginId': typeof AppPluginsPluginIdRoute
  '/_app/settings/$path': typeof AppSettingsPathRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/organizations/': typeof AppOrganizationsIndexRoute
  '/_app/plugins/': typeof AppPluginsIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/organization/$slug/$path': typeof AppOrganizationSlugPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/$'
    | '/auth/$path'
    | '/.well-known/oauth-authorization-server/$'
    | '/organizations/$organizationId'
    | '/plugins/$pluginId'
    | '/settings/$path'
    | '/users/$userId'
    | '/organizations/'
    | '/plugins/'
    | '/users/'
    | '/organization/$slug/$path'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/api/$'
    | '/auth/$path'
    | '/'
    | '/.well-known/oauth-authorization-server/$'
    | '/organizations/$organizationId'
    | '/plugins/$pluginId'
    | '/settings/$path'
    | '/users/$userId'
    | '/organizations'
    | '/plugins'
    | '/users'
    | '/organization/$slug/$path'
  id:
    | '__root__'
    | '/_app'
    | '/dashboard'
    | '/api/$'
    | '/auth/$path'
    | '/_app/'
    | '/.well-known/oauth-authorization-server/$'
    | '/_app/organizations/$organizationId'
    | '/_app/plugins/$pluginId'
    | '/_app/settings/$path'
    | '/_app/users/$userId'
    | '/_app/organizations/'
    | '/_app/plugins/'
    | '/_app/users/'
    | '/_app/organization/$slug/$path'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthPathRoute: typeof AuthPathRoute
  DotwellKnownOauthAuthorizationServerSplatRoute: typeof DotwellKnownOauthAuthorizationServerSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server/$': {
      id: '/.well-known/oauth-authorization-server/$'
      path: '/.well-known/oauth-authorization-server/$'
      fullPath: '/.well-known/oauth-authorization-server/$'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/organizations/': {
      id: '/_app/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/$organizationId': {
      id: '/_app/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plugins/': {
      id: '/_app/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof AppPluginsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plugins/$pluginId': {
      id: '/_app/plugins/$pluginId'
      path: '/plugins/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof AppPluginsPluginIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/$path': {
      id: '/_app/settings/$path'
      path: '/settings/$path'
      fullPath: '/settings/$path'
      preLoaderRoute: typeof AppSettingsPathRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization/$slug/$path': {
      id: '/_app/organization/$slug/$path'
      path: '/organization/$slug/$path'
      fullPath: '/organization/$slug/$path'
      preLoaderRoute: typeof AppOrganizationSlugPathRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppOrganizationsOrganizationIdRoute: typeof AppOrganizationsOrganizationIdRoute
  AppPluginsPluginIdRoute: typeof AppPluginsPluginIdRoute
  AppSettingsPathRoute: typeof AppSettingsPathRoute
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
  AppPluginsIndexRoute: typeof AppPluginsIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppOrganizationSlugPathRoute: typeof AppOrganizationSlugPathRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppOrganizationsOrganizationIdRoute: AppOrganizationsOrganizationIdRoute,
  AppPluginsPluginIdRoute: AppPluginsPluginIdRoute,
  AppSettingsPathRoute: AppSettingsPathRoute,
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
  AppPluginsIndexRoute: AppPluginsIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppOrganizationSlugPathRoute: AppOrganizationSlugPathRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthPathRoute: AuthPathRoute,
  DotwellKnownOauthAuthorizationServerSplatRoute:
    DotwellKnownOauthAuthorizationServerSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
